version: "3.7"
services:

  #Service PHP
  app:
    build:
      args:
        user: dean
        uid: 1001
      context: ./.docker
      dockerfile: Dockerfile
    image: laravelapp
    container_name: laravelapp-app1
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravelapp

  #Service MySQL
  db:
    image: mysql:5.7
    container_name: laravelapp-db1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'lara_db'
      MYSQL_ROOT_PASSWORD: 'root'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravelapp

  #Service Nginx
  nginx:
    image: nginx:1.17-alpine
    container_name: laravelapp-nginx1
    restart: unless-stopped
    ports:
      - 8008:80
    volumes:
      - ./src:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - laravelapp

networks:
  laravelapp:
    driver: bridge